---
# tasks for freebsd_mailserver

- name: Import debug.yml
  ansible.builtin.import_tasks: debug.yml
  when: fm_debug|bool
  tags: fm-debug

- name: Import packages.yml
  ansible.builtin.import_tasks: packages.yml
  when: fm_install|bool
  tags: fm-packages

- name: Import files.yml
  ansible.builtin.import_tasks: files.yml
  tags: fm-files

- name: Import dirs.yml
  ansible.builtin.import_tasks: dirs.yml
  tags: fm-dirs

- name: Import sanity.yml
  ansible.builtin.import_tasks: sanity.yml
  when: fm_sanity|bool
  tags: fm-sanity

- name: Import certificates.yml
  ansible.builtin.import_tasks: certificates.yml
  tags: fm-certificates

- name: Import rcconf.yml
  ansible.builtin.import_tasks: rcconf.yml
  tags: fm-rcconf

- name: Import cloud_provider.yml
  ansible.builtin.import_tasks: cloud_provider.yml
  tags: fm-cloud

- name: Import mailer_conf.yml
  ansible.builtin.import_tasks: mailer_conf.yml
  tags: fm-mailer_conf

- name: Import periodic_conf.yml
  ansible.builtin.import_tasks: periodic_conf.yml
  tags: fm-periodic_conf

- name: Import postfix.yml
  ansible.builtin.import_tasks: postfix.yml
  tags: fm-postfix

- name: Import postfix_sasl.yml
  ansible.builtin.import_tasks: postfix_sasl.yml
  tags: fm-postfix_sasl

- name: Import postifix_master.yml
  ansible.builtin.import_tasks: postfix_master.yml
  tags: fm-postfix_master

- name: Import spf.yml
  ansible.builtin.import_tasks: spf.yml
  tags: fm-spf

- name: Import dkim.yml
  ansible.builtin.import_tasks: dkim.yml
  tags: fm-dkim

- name: Import virtual_aliases.yml
  ansible.builtin.import_tasks: virtual_aliases.yml
  tags: fm-virtual_aliases

- name: Import aliases.yml
  ansible.builtin.import_tasks: aliases.yml
  tags: fm-aliases

- name: Import dovecot.yml
  ansible.builtin.import_tasks: dovecot.yml
  tags: fm-dovecot

- name: Import procmail.yml
  ansible.builtin.import_tasks: procmail.yml
  when: fm_procmail_enable|bool
  tags: fm-procmail

# EOF
...
